import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Aleo } from "next/font/google";

const aleo = Aleo({ subsets: ["latin"], variable: "--font-aleo" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={aleo.variable}>
                <Theme
                    appearance='light'
                    accentColor='bronze'
                    grayColor='sage'
                    radius='large'
                >
                    {" "}
                    <main>{children}</main>
                    {/* <ThemePanel /> */}
                </Theme>
            </body>
        </html>
    );
}
